import os
import sys
import time
import uuid


sample = '''
# Generated by manim_helper at {}

from manim import *

import manim_helper

class {}(Scene):

    def prepare(self) -> None:
        loader = manim_helper.TextLoader("{}")
        text_data = loader.load()
        self.objects = loader.apply(text_data)
        self.director = manim_helper.Director(self.objects, "{}")

    def construct(self) -> None:
        self.prepare()
        self.director.set_target_show(self)
        self.director.load_actions()
        self.director.start_play()   
'''


    
if __name__ == '__main__':
    if len(sys.argv) != 4:
        sys.stderr.write(f'Usage: ./{sys.argv[0]} <scene> <script-file> <actions-file>')

    __scene_name__ = sys.argv[1]
    script = sys.argv[2]
    actions = sys.argv[3]

    filename = f'{uuid.uuid1()}__cache.py'
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(sample.format(
            time.strftime('%y-%m-%d_%H-%M-%S', time.localtime(time.time())),
            __scene_name__, script, actions
        ))

    os.system(f'manim -p "{filename}" {__scene_name__}')
    os.remove(filename)
